services:
  postgres:
    image: postgres:16
    container_name: documentjob_postgres
    restart: always
    environment:
      POSTGRES_DB: documentjobdb
      POSTGRES_USER: document_user
      POSTGRES_PASSWORD: document_password
    ports:
      - "5432:5432"
    volumes:
      - documentjob_pgdata:/var/lib/postgresql/data

volumes:
  documentjob_pgdata:
