@HostAddress = http://localhost:5031

### Send GET with ID to retrieve a particular job
GET {{HostAddress}}/api/jobs/14
Accept: application/json

### Send GET to list all jobs
GET {{HostAddress}}/api/jobs
Accept: application/json

### Send POST request with json body
POST http://{{HostAddress}}/api/jobs
Content-Type: application/json

{
  "InputText": "Input Text 13"
}

### Send POST request with json body
POST http://{{HostAddress}}/api/jobs
Content-Type: application/json

{
  "InputText": "This is a slightly more complex test document.\nIt contains multiple lines, some punctuation, and a few longer words.\nThe goal is to verify that analysis logic correctly counts words, characters, and lines.\n"
}
