@HostAddress = http://localhost:5031

### Send GET with ID to retrieve a particular job
GET {{HostAddress}}/api/jobs/5
Accept: application/json

### Send GET to list all jobs
GET {{HostAddress}}/api/jobs
Accept: application/json

### Send POST request with json body
POST http://{{HostAddress}}/api/jobs
Content-Type: application/json

{
  "InputText": "Test Document 10"
}